Repository Code-Hills/codehills-be, pull requests merged in 2023-06, with the labels that each got.

#30 chore: make end of line auto
  .eslintignore
  .eslintrc.json
  .prettierrc
  package.json
Labels: Ready to merge

#34 Get all reviewers in the given review cycle
  src/database/seeders/some-reviewers.js
  src/documentation/review/index.js
  src/restful/controllers/reviewControllers.js
  src/restful/routes/reviewRouter.js
  src/services/reviewServices.js
Labels: Review needed

#32 feat: add dashboard endpoint
  src/database/seeders/1-users.js
  src/documentation/auth/dashboard.js
  src/documentation/index.js
  src/restful/controllers/DashboardController.js
  src/restful/routes/dashboard.js
  src/restful/routes/index.js
  src/services/DashboardService.js
Labels: Review needed

#35 Ft enhance get reviewers
  src/documentation/review/index.js
  src/restful/controllers/reviewControllers.js
  src/restful/routes/userRoutes.js
  src/services/reviewServices.js
Labels: enhancement, Review needed
